reminder: true
minify: true
darkmode: true
language_switcher: true
cache: 
  enable: false
favicon: 
  /img/favicon.jpg # TODO change to my posts

footer: 
  since: 2020
  icon: 
    animated: true

creative_commons: # 文章原创申明
  sidebar: true    # 显示在sidebar里面，可选
  post: true  # 默认,在底部显示版权信息

auto_excerpt:   # 是否自动截取摘要 
  enable: true # 设置为true则自动截取150字当做首页摘要 false的话得在正文里面写<!--more--> 进行分割，否则就是整篇出来...
  length: 150   # 自动截取的字数

scheme: Gemini
# scheme: Pisces 

menu:
  home: / || fa fa-home
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  tags: /tags || fa fa-tag
menu_settings: 
  badges: true

avatar: 
  url: /img/avatar-hexi.jpg

social: # 社交名字: 社交url || 社交图标
  GitHub: https://github.com/hexi519 || fab fa-github
  E-Mail: mailto:hesy519@gmail.com || fa fa-envelope
  CSDN: https://blog.csdn.net/Hesy_H || fab fa-plug

reward_settings:
  enable: true
  animation: true

reward: #  配置微信，支付宝打赏 
  wechatpay: /img/WechatPay.jpg
  alipay: /img/AliPay.jpg

related_posts:
   enable: false

post_edit: # 大概是源文件存档在哪儿（点击界面右上角就可以link过去的）
  enable: true
  url: https://github.com/hexi519/hexi519.github.io/ # Link for view source.

codeblock:  # 内容页里的代码块新增复制按钮
  copy_button:
    enable: true  # 增加复制按钮的开
    show_result: true   # 点击复制完后是否显示 复制成功 结果提示

reading_progress:
  enable: true

bookmark:
  enable: true

github_banner: # 点击界面右上角猫咪就可以link到github主页
  enable: true
  permalink: https://github.com/hexi519/

seo: true
index_with_subtitle: true
exturl: true
math:
  enable: true 
  mathjax:
    enable: true
    per_page: true

local_search:
  enable: true

pdf:
  enable: true

links_settings: # 设置友链
  icon: fa fa-link
  title: Friend Links
  layout: block
links:
  "学神(Jinzhe Zeng)": http://njzjz.win

tagcloud: true  # 

# 关闭动画效果
three_waves: false
canvas_nest: false

vendors:
  velocity: //js.njzjz.win/npm/velocity-animate@1/velocity.min.js
  velocity_ui: //js.njzjz.win/npm/velocity-animate@1/velocity.ui.min.js
  internal: jsdelivr
  plugins: jsdelivr


# valine: # 评论功能 还得注册appid相关的,which 我就先不了把
#   enable: true
#   appid: 
#   appkey: 
#   notify: true
#   visitor: true
#   recordIP: true
#   enableQQ: true
#   serverURLs: 

# google_analytics: 
#   tracking_id: