reminder: true
minify: true
darkmode: true
language_switcher: true
cache: 
  enable: false
favicon: 
  /img/favicon.jpg # TODO change to my posts

footer: 
  since: 2020
  icon: 
    animated: true

creative_commons: # 文章原创申明
  sidebar: true    # 显示在sidebar里面，可选
  post: true  # 默认,在底部显示版权信息

auto_excerpt:   # 是否自动截取摘要 
  enable: true # 设置为true则自动截取150字当做首页摘要 false的话得在正文里面写<!--more--> 进行分割，否则就是整篇出来...
  length: 150   # 自动截取的字数

scheme: Gemini
# scheme: Pisces 

menu:
  home: / || fa fa-home
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  tags: /tags || fa fa-tag
menu_settings: 
  badges: true

avatar: 
  url: /img/avatar-hexi.jpg

social: # 社交名字: 社交url || 社交图标
  GitHub: https://github.com/hexi519 || fab fa-github
  E-Mail: mailto:hesy519@gmail.com || fa fa-envelope
  CSDN: https://blog.csdn.net/Hesy_H || fab fa-plug

reward_settings:
  enable: true
  animation: true

reward: #  配置微信，支付宝打赏 
  wechatpay: /img/WechatPay.jpg
  alipay: /img/AliPay.jpg

related_posts:
   enable: false

post_edit: # 大概是源文件存档在哪儿（点击界面右上角就可以link过去的）
  enable: true
  url: https://github.com/hexi519/hexi519.github.io/ # Link for view source.

codeblock:  # 内容页里的代码块新增复制按钮
  copy_button:
    enable: true  # 增加复制按钮的开
    show_result: true   # 点击复制完后是否显示 复制成功 结果提示

reading_progress:
  enable: true

bookmark:
  enable: true

github_banner: # 点击界面右上角猫咪就可以link到github主页
  enable: true
  permalink: https://github.com/hexi519/

seo: true
index_with_subtitle: true
exturl: true
math:
  enable: true 

local_search:
  enable: true

pdf:
  enable: true

links_settings: # 设置友链
  icon: fa fa-link
  title: Friend Links
  layout: block
links:
  "学神(Jinzhe Zeng)": http://njzjz.win

tagcloud: true  # 

# 关闭动画效果
three_waves: false
canvas_nest: false

vendors:
  anime: //js.njzjz.win/npm/animejs@3.1.0/lib/anime.min.js
  fontawesome: //js.njzjz.win/npm/@fortawesome/fontawesome-free@5/css/all.min.css
  mathjax: https://cdn.bootcss.com/mathjax/2.7.0/MathJax.js
  mhchem: //js.njzjz.win/npm/mathjax-mhchem@3
  katex: //js.njzjz.win/npm/katex@0/dist/katex.min.css
  copy_tex_js: //js.njzjz.win/npm/katex@0/dist/contrib/copy-tex.min.js
  pjax: //js.njzjz.win/gh/theme-next/theme-next-pjax@0/pjax.min.js
  jquery: //js.njzjz.win/npm/jquery@3/dist/jquery.min.js
  fancybox: //js.njzjz.win/gh/fancyapps/fancybox@3/dist/jquery.fancybox.min.js
  fancybox_css: //js.njzjz.win/gh/fancyapps/fancybox@3/dist/jquery.fancybox.min.css
  mediumzoom: //js.njzjz.win/npm/medium-zoom@1/dist/medium-zoom.min.js
  lazyload: //js.njzjz.win/npm/lozad@1/dist/lozad.min.js
  pangu: //js.njzjz.win/npm/pangu@4/dist/browser/pangu.min.js
  quicklink: //js.njzjz.win/npm/quicklink@1/dist/quicklink.umd.js
  disqusjs_js: //js.njzjz.win/npm/disqusjs@1/dist/disqus.js
  disqusjs_css: //js.njzjz.win/npm/disqusjs@1/dist/disqusjs.css
  valine: //js.njzjz.win/npm/valine@1/dist/Valine.min.js
  gitalk_js: //js.njzjz.win/npm/gitalk@1/dist/gitalk.min.js
  gitalk_css: //js.njzjz.win/npm/gitalk@1/dist/gitalk.css
  algolia_instant_js: //js.njzjz.win/npm/instantsearch.js@2/dist/instantsearch.min.js
  algolia_instant_css: //js.njzjz.win/npm/instantsearch.js@2/dist/instantsearch.min.css
  pdfobject: //js.njzjz.win/npm/pdfobject@2/pdfobject.min.js
  mermaid: //js.njzjz.win/npm/mermaid@8/dist/mermaid.min.js
  velocity: //js.njzjz.win/npm/velocity-animate@1/velocity.min.js
  velocity_ui: //js.njzjz.win/npm/velocity-animate@1/velocity.ui.min.js
  pace: //js.njzjz.win/npm/pace-js@1/pace.min.js
  pace_css: //js.njzjz.win/npm/pace-js@1/themes/blue/pace-theme-minimal.css
  three: //js.njzjz.win/gh/theme-next/theme-next-three@1/three.min.js
  # three_waves: //js.njzjz.win/gh/theme-next/theme-next-three@1/three-waves.min.js
  canvas_lines: //js.njzjz.win/gh/theme-next/theme-next-three@1/canvas_lines.min.js
  canvas_sphere: //js.njzjz.win/gh/theme-next/theme-next-three@1/canvas_sphere.min.js
  # canvas_nest: //js.njzjz.win/gh/theme-next/theme-next-canvas-nest@1/canvas-nest.min.js
  # canvas_nest_nomobile: //js.njzjz.win/gh/theme-next/theme-next-canvas-nest@1/canvas-nest-nomobile.min.js
  canvas_ribbon: //js.njzjz.win/gh/theme-next/theme-next-canvas-ribbon@1/canvas-ribbon.js

# valine: # 评论功能 
#   enable: true
#   appid: 
#   appkey: 
#   notify: true
#   visitor: true
#   recordIP: true
#   serverURLs: 

# google_analytics: 
#   tracking_id: